- name: Desktop environment
  hosts: odhosts
  tasks:
   - name: Install KDE
     become: true
     ansible.builtin.apt:
       pkg:
         - kde-plasma-desktop
         - kate
         - okular
         - dolphin
