- name: Development environment
  hosts: odhosts
  tasks:
    - name: Install essential cmd tools - alacritty, git, tmux,
      become: true
      ansible.builtin.apt:
        pkg:
          - alacritty
          - git
          - tmux
    - name: Install build tools - make, cmake, gcc, g++, clang, libc6-dev
      become: true
      ansible.builtin.apt:
        pkg:
          - make
          - cmake
          - gcc
          - g++
          - clang
          - libc6-dev
    - name: Enable debian bookworm backports
      become: true
      ansible.builtin.apt_repository:
        repo: deb http://deb.debian.org/debian bookworm-backports main
        state: present
        filename: backports
    - name: Install golang from backports
      become: true
      ansible.builtin.apt:
        name: golang
        default_release: bookworm-backports
    - name: Install python
      become: true
      ansible.builtin.apt:
        pkg:
          - python3
          - python3-venv
          - python3-pip
    - name: Install docker and docker-compose
      become: true
      ansible.builtin.apt:
        pkg:
          - docker
          - docker-compose
